/**
 * @file src/webrtc/weriftSession.ts
 * @description This file contains the WeriftWebRtcSession class, wrapping a werift RTCPeerConnection.
 * @author Ludovic BOUÉ
 * @created 2026-07-14
 * @version 1.0.0
 * @license Apache-2.0
 *
 * Copyright 2026, 2027, 2028 Luca Liguori.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { RTCPeerConnection } from 'werift';

/**
 * Media kinds to negotiate when creating a real WebRTC offer for a WebRtcTransportProvider session.
 */
export interface WeriftOfferOptions {
  /** Whether to add a sendonly video transceiver to the offer. */
  video: boolean;
  /** Whether to add a sendonly audio transceiver to the offer. */
  audio: boolean;
}

/**
 * Wraps a werift RTCPeerConnection for a single WebRtcTransportProvider session (see
 * MatterbridgeWebRtcTransportProviderServer in ../behaviors/webRtcTransportProviderServer.ts), so the session's SDP
 * offer is generated by a real WebRTC peer connection instead of a placeholder string.
 *
 * This currently only covers offer generation and connection teardown: it does not yet apply a remote SDP answer,
 * apply trickled ICE candidates, or attach an encoded media track to the negotiated transceivers, so no RTP flows
 * once negotiated. Those are follow-up steps once this offer-generation slice has been validated end to end.
 */
export class WeriftWebRtcSession {
  /** The underlying werift peer connection for this session. */
  readonly peerConnection: RTCPeerConnection;

  constructor() {
    this.peerConnection = new RTCPeerConnection();
  }

  /**
   * Adds a sendonly transceiver for each requested media kind and creates a real local SDP offer.
   *
   * @param {WeriftOfferOptions} options - Which media kinds to add a sendonly transceiver for.
   * @returns {Promise<string>} The generated local SDP offer.
   */
  async createOffer(options: WeriftOfferOptions): Promise<string> {
    if (options.video) this.peerConnection.addTransceiver('video', { direction: 'sendonly' });
    if (options.audio) this.peerConnection.addTransceiver('audio', { direction: 'sendonly' });
    const offer = await this.peerConnection.createOffer();
    await this.peerConnection.setLocalDescription(offer);
    return this.peerConnection.localDescription?.sdp ?? offer.sdp;
  }

  /**
   * Closes the underlying peer connection.
   *
   * @returns {Promise<void>} Resolves once the peer connection is closed.
   */
  async close(): Promise<void> {
    await this.peerConnection.close();
  }
}
